// frontend/src/components/ShoppingList/ShoppingListItem.vue
<template>
  <div class="flex flex-col h-32 rounded-md bg-gray-800 space-y-2">
    <div class="flex flex-shrink justify-center mt-1">
      <img
        src="https://web.getbring.com/assets/images/items/konfituere.png"
        alt=""
        class="h-14"
      />
    </div>
    <div class="flex h-14 items-end justify-center m-1">
      <span
        class="text-white text-sm leading-4 overflow-hidden overflow-ellipsis break-words line-clamp-2"
      >
        {{ name }}
      </span>
    </div>
    <div class="flex h-8 overflow-hidden flex-col text-center">
      <span class="text-gray-400 text-xs">{{ description }}</span>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
  name: "ShoppingListItem",
  props: {
    _id: {
      type: String,
      required: true,
    },
    name: {
      type: String,
      required: true,
    },
    description: {
      type: String,
      default: "",
    },
  },
  setup() {},
});
</script>

<style>
</style>

// src/components/shoppinglistitem.tsx
import { PureComponent } from 'react';

export type ShoppingListItemProps = {
    _id: string;
    name: string;
    description: string;
};

class ShoppingListItem extends PureComponent<ShoppingListItemProps> {
    render() {
        return (
            <div className="flex flex-col h-32 rounded-md bg-gray-800 space-y-2">
                <div className="flex flex-shrink justify-center mt-1">
                    <img src="https://web.getbring.com/assets/images/items/konfituere.png" alt="" className="h-14" />
                </div>
                <div className="flex h-14 items-end justify-center m-1">
                    <span className="text-white text-sm leading-4 overflow-hidden overflow-ellipsis break-words line-clamp-2">
                        {this.props.name}
                    </span>
                </div>
                <div className="flex h-8 overflow-hidden flex-col text-center">
                    <span className="text-gray-400 text-xs">{this.props.description}</span>
                </div>
            </div>
        );
    }
}

export default ShoppingListItem;
